---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---
# load packages
```{r}
require(readr)
require(readxl)
require(lavaan)
library(DiagrammeR)
library(dplyr)
library(plyr)
library(tidyr)
library(ggplot2)
library(semPlot)
library(psych)
library(sem)
library(semTools)
```

# loading data
```{r include=TRUE,echo=TRUE}
data_of_xiaojuan_yang <- read_excel("D:/Data_analisis/xiaojuan_yang/data_of_xiaojuan_yang.xls",sheet = "total")
data_of_xiaojuan_yang<-data_of_xiaojuan_yang[,-1]
View(data_of_xiaojuan_yang)
#对各分级指标做因子分析，查看题目必要性
#A_2
fa.parallel(data_of_xiaojuan_yang[,c(2:7)],fa = "pc",n.iter = 100,show.legend = TRUE,main = "A_2主成分分析")

principal(data_of_xiaojuan_yang[,c(2:7)],nfactors = 1,rotate = "varimax",scores = TRUE)

#A_3
fa.parallel(data_of_xiaojuan_yang[,c(8:14)],fa = "pc",n.iter = 100,show.legend = TRUE,main = "A_3主成分分析")

principal(data_of_xiaojuan_yang[,c(8:14)],nfactors = 2)

#B_1

fa.parallel(data_of_xiaojuan_yang[,c(15:21)],fa = "pc",n.iter = 100,show.legend = TRUE,main = "B_1主成分分析")

principal(data_of_xiaojuan_yang[,c(15:21)],nfactors = 1)

#B_2
fa.parallel(data_of_xiaojuan_yang[,c(22:23)],fa = "pc",n.iter = 100,show.legend = TRUE,main = "B_2主成分分析")

principal(data_of_xiaojuan_yang[,c(22:23)],nfactors = 1)

#B_3
fa.parallel(data_of_xiaojuan_yang[,c(24:30)],fa = "pc",n.iter = 100,show.legend = TRUE,main = "B_3主成分分析")

principal(data_of_xiaojuan_yang[,c(24:30)],nfactors = 1)

#B_4
fa.parallel(data_of_xiaojuan_yang[,c(31:33)],fa = "pc",n.iter = 100,show.legend = TRUE,main = "B_4主成分分析")

principal(data_of_xiaojuan_yang[,c(31:33)],nfactors = 1)
#B_5
fa.parallel(data_of_xiaojuan_yang[,c(34:36)],fa = "pc",n.iter = 100,show.legend = TRUE,main = "B_5主成分分析")

principal(data_of_xiaojuan_yang[,c(34:36)],nfactors = 1)

#C
fa.parallel(data_of_xiaojuan_yang[,c(37:38)],fa = "pc",n.iter = 100,show.legend = TRUE,main = "C主成分分析")

principal(data_of_xiaojuan_yang[,c(37:38)],nfactors = 1)

#D
fa.parallel(data_of_xiaojuan_yang[,c(39:44)],fa = "pc",n.iter = 100,show.legend = TRUE,main = "D主成分分析")

principal(data_of_xiaojuan_yang[,c(39:44)],nfactors = 1)

#E
fa.parallel(data_of_xiaojuan_yang[,c(45:46)],fa = "pc",n.iter = 100,show.legend = TRUE,main = "E主成分分析")

principal(data_of_xiaojuan_yang[,c(45:46)],nfactors = 1)

#F
fa.parallel(data_of_xiaojuan_yang[,c(47:48)],fa = "pc",n.iter = 100,show.legend = TRUE,main = "F主成分分析")

principal(data_of_xiaojuan_yang[,c(47:48)],nfactors = 1)

#选取新变量组成数据框
A_1<-data_of_xiaojuan_yang$A_1
A_2<-data_of_xiaojuan_yang$A_2_2
A_3<-(data_of_xiaojuan_yang$A_3_1+data_of_xiaojuan_yang$A_3_2)/2
A<-(A_1+A_2+A_3)/3
B_1<-(data_of_xiaojuan_yang$B_1_6+data_of_xiaojuan_yang$B_1_5)/2
B_2<-(data_of_xiaojuan_yang$B_2_1+data_of_xiaojuan_yang$B_2_2)/2
B_3<-(data_of_xiaojuan_yang$B_3_4+data_of_xiaojuan_yang$B_3_5)/2
B_4<-(data_of_xiaojuan_yang$B_4_2+data_of_xiaojuan_yang$B_4_1+data_of_xiaojuan_yang$B_4_3)/3
B_5<-data_of_xiaojuan_yang$B_5_2
B<-(B_1+B_2+B_3+B_4+B_5)/5
C<-(data_of_xiaojuan_yang$C_1+data_of_xiaojuan_yang$C_2)/2
D<-(data_of_xiaojuan_yang$D_4+data_of_xiaojuan_yang$D_1+data_of_xiaojuan_yang$D_5)/3
E<-(data_of_xiaojuan_yang$E_1+data_of_xiaojuan_yang$E_2)/2
F_1<-(data_of_xiaojuan_yang$F_1+data_of_xiaojuan_yang$F_2)/2
G<-data_of_xiaojuan_yang$G_1

#数据框

yang_data_final<-data.frame(A_1,A_2,A_3,B_1,B_2,B_3,B_4,B_5,C,D,E,F_1,G)
head(yang_data_final)
yang_data_final_1<-data.frame(A,B,C,D,E,F_1,G)
View(yang_data_final_1)

write.csv(yang_data_final,file = "D:/Data_analisis/xiaojuan_yang/data_of_xiaojuan_yang_final.csv")
#清洗数据

yang_data_final_boxplot<-gather(yang_data_final,class_of_data,value_of_data)

ggplot(data = yang_data_final_boxplot,aes(x=class_of_data,y=value_of_data))+geom_boxplot()+geom_jitter(aes(color=class_of_data),alpha=0.2)+theme_bw()


```

# model set
```{r include=TRUE,echo=TRUE}
# model 1
modeltext<-'
A=~A_1+A_2+A_3
B=~B_1+B_2+B_3+B_4+B_5

A~~0*B

B~A
C~A+B
D~C+B
E~B
F_1~D+E
G~C+D+F_1
'
fitdata<-lavaan::sem(modeltext,yang_data_final)

semPaths(fitdata,what = "col",whatLabels = "stand",layout = "tree",style = "OpenMx",rotation = 4)

modificationIndices(fitdata,sort. = TRUE)
modindices(fitdata)
parameterEstimates(fitdata)
parameterTable(fitdata)
standardizedSolution(fitdata)

semCors(fitdata)
semPlotModel(fitdata)

moreFitIndices(fitdata)
nullRMSEA(fitdata)
miPowerFit(fitdata)
chisqSmallN(fitdata)

```




